/obj/secure_closet/captains/New()
	..()
	sleep(2)
	new /obj/item/weapon/storage/id_kit( src )
	new /obj/item/clothing/under( src )
	new /obj/item/clothing/shoes/brown( src )
	new /obj/item/clothing/glasses/sunglasses( src )
	new /obj/item/clothing/suit/armor/vest( src )
	new /obj/item/clothing/head/helmet/swat( src )
	return
