/obj/closet/gmcloset/New()
	..()
	sleep(2)
	new /obj/item/clothing/head/that(src)
	new /obj/item/clothing/head/that(src)
	new /obj/item/clothing/under(src)
	new /obj/item/clothing/under(src)
	new /obj/item/clothing/under(src)
	new /obj/item/clothing/under(src)
	new /obj/item/clothing/suit/wcoat(src)
	new /obj/item/clothing/suit/wcoat(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/clothing/shoes/black(src)
